### ISSUE TITLE
Package for CentOS Stream 8

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/ui-metapackage#3]
Package for CentOS Stream 8.

UMD is not available for Stream 8.
Using EPEL 8, at least those packages are missing:
* gfal2-python
* ca-policy-egi-core
* condor
* dcache-srmclient
* fts-client
* gfalFS
* ginfo
* lcg-ManageVOTag
* lcg-info
* lcg-tags

**Comment by gwarf** [comment]
@paolini78, @andrea-manzi may be this should be closed as won't do and only plan #4?
What do you think?

**Comment by andrea-manzi** [comment]
are we going to have UMD 5 with centos Stream 8 or directly with Centos Stream 9?

**Comment by paolini78** [comment]
CENTOS8 is not in the UMD plans, so you can close this task

**Comment by gwarf** [comment]
Closing, won't do.
